apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-service-c
  namespace: argocd

  annotations:
    argocd-image-updater.argoproj.io/image-list: python-service-c=d4rkghost47/python-circuit-svc-3
    argocd-image-updater.argoproj.io/python-service-c.update-strategy: newest-build
    argocd-image-updater.argoproj.io/python-service-c.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/python-service-c.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:values.yaml

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: git@github.com:evil-cloud/resillience-poc-service-c-k8s.git
    targetRevision: HEAD
    path: .
    helm:
      valueFiles:
        - values.yaml
      skipSchemaValidation: false
      skipCrds: false

  destination:
    server: https://kubernetes.default.svc
    namespace: circuit-breaker-app-v2

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - ignoreMissingValueFiles=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 5
